fix: 깃허브 액션 들여쓰기 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,15 +13,14 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-    - name: SSH into server and deploy
-  uses: appleboy/ssh-action@v0.1.9
-  with:
-    host: ${{ secrets.SSH_HOST }}
-    username: ${{ secrets.SSH_USERNAME }}
-    password: ${{ secrets.SSH_PASSWORD }}
-    port: 22
-    script: |
-      cd /commitbody
-      git pull origin main || echo "Git pull failed"
-      echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose -f docker-compose.blue.yml up -d --build
-
+      - name: SSH into server and deploy
+        uses: appleboy/ssh-action@v0.1.9
+        with:
+          host: ${{ secrets.SSH_HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          password: ${{ secrets.SSH_PASSWORD }}
+          port: 22
+          script: |
+            cd /commitbody
+            git pull origin main || echo "Git pull failed"
+            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose -f docker-compose.blue.yml up -d --build
